### ISSUE TITLE
An error in the table of numbers of spherical harmonics in README

### ISSUE THREAD

**Issue by pkfancy** [vdutor/SphericalHarmonics#20]
Running `num_harmonics()` in `fundamental_set.py`, we get all results correct, e.g., `num_harmonics(3 + 1, 34 - 1) = 1156, num_harmonics(4 + 1, 20 - 1) = 2870, ...`, except one, which is `num_harmonics(5 + 1, 10 - 1) = 1210`. I mean, `(5, 10, 16170)` is not correct, and it should be `(5, 10, 1210)`

**Comment by stoprightthere** [comment]
Hi @pkfancy , thanks for catching this!
